### ISSUE TITLE
Vercel CLI 33.6.0 deploy failing with error: Invalid request: `projectSettings.nodeVersion` should be equal to one of the allowed values "20.x, 18.x, 16.x".

### ISSUE THREAD

**Issue by Zhaph** [zeit/now#11285]
Our CI/CD deployments started failing this morning when they upgraded the version of the CLI used from 33.5.5 to 33.6.0.

Attempting to pull the repo and deploy using:

```
- task: bash@3
  displayName: 'Deploy Front End to Vercel Production'
  inputs:
    targetType: 'inline'
    script: |
      npm install -g vercel
      vercel --version
      vercel deploy --prod --token ${{ parameters.VercelToken }}
  env:
    VERCEL_ORG_ID: ${{ parameters.VercelTeamId }}
    VERCEL_PROJECT_ID: ${{ parameters.VercelProjectId }}
```

Now results in:

> Error: Invalid request: `projectSettings.nodeVersion` should be equal to one of the allowed values "20.x, 18.x, 16.x".

Previously this worked as expected and deployed successfully.

The Project referenced in the `VERCEL_PROJECT_ID` environment variable has it's node version set to `18.x`.
