### ISSUE TITLE
Serverless function crashed — express app, issue on obsfucation of Javascript.

### ISSUE THREAD

**Issue by victoryosiobe** [zeit/now#11856]
I  use GitHub actions to obsfucate all JavaScripts of a branch. Including minification of some other files, (HTML, CSS—only). Now that action is done from a `master-twin` branch. This action on push obfuscates, minifies and removes the workflow file, then force push to production branch, master. I deployed to Render (hosting & server) on the `master` branch and everything works fine. But I also at same time want deploy to Vercel as Render has some draw backs.

Due to simplicity and way this is all built, this is possible with no conflict, however, Render deploys and the Express App works fine. On the Vercel end, I get a 500 code on `master` branch. Same branch that works on Render. But if I switch branch to `master-twin` branch on Vercel for deployment, it works. Certainly a Vercel issue.

My logs show errors importing node packages. Looked up the package.json. It lists them same on both branches correctly. The package.json isn't even getting minified, so no changes to it.

What's more? After redeploying a couple of times. I get random “could not find modules,” sometimes it's express, cors, mathjs...while not changing anything, just redeploying. Recently, I tried again. This time, a path, not a module, couldn't be found (fig: oops

![Screenshot_2024_0715_035130](https://github.com/user-attachments/assets/93ace3e1-b766-4797-afaa-61a82b46438b)

![Screenshot_2024_0715_035213](https://github.com/user-attachments/assets/368edc75-f549-445d-bc45-89ae91040897)

**Fig oops**

> ![Screenshot_2024_0715_174136](https://github.com/user-attachments/assets/746862ac-81e0-45c5-bfea-4c5688111010)
> ![Screenshot_2024_0715_174218](https://github.com/user-attachments/assets/794cb147-dbdd-4f1d-8eff-ce97e19fb8da)
> ![Screenshot_2024_0715_174854](https://github.com/user-attachments/assets/dd76274a-79a4-43de-9260-b5156c928a5e)

Issue with package.json? No. How does obsfucation affect Vercel while Render is deploying same obsfucated branch successfully. There's no change to folder structure except a removal of the github workflow file from `master` with is at root and removed at root.

![Screenshot_20240715_034358](https://github.com/user-attachments/assets/b12e6de5-cfb0-4342-b00d-713b7610799a)

I can't display the `package.json` because of some policies, but that not the issue. 

In all, build logs, and deployment is showing success, but serverless function crashes.

**File Structure**:

```text

api/
  | index.js
utils/
...
vercel.json

```

**Vercel.json**:

```json

{ "version": 2, "rewrites": [{ "source": "/(.*)", "destination": "/api" }] }

```

**My workflow file**:

```yaml

name: Obfuscate JS and CSS, Minify HTML

on:
  push:
    branches:
      - master-twin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Check out code
        uses: actions/checkout@v4
        with:
         repository: victoryosiobe/syntaxx
         token: ${{ secrets.GIT_PAT }}

      - name: Install Dependencies
        run: |
           npm install javascript-obfuscator -g
           npm install clean-css-cli -g
           npm install html-minifier -g

      - name: Obfuscate JavaScript
        run: |
          find . -type f -name '*.js' -exec javascript-obfuscator {} -o {} \;

      - name: Obfuscate CSS
        run: |
          find . -type f -name '*.css' -exec cleancss {} -o {} \;

      - name: Minify HTML
        run: |
          find . -type f -name '*.html' -exec html-minifier {} -o {} \;
 
      - name: Git Config
        run: |
          git config --global user.email "<email>"
          git config --global user.name "victoryosiobe"

      - name: Remove Workflow File Before Commiting and Pushing To Prevent Conflicts
        run: |
           cd .github/workflows 
           rm action-first.yaml
           
      - name: Git stage and commit
        run: |
          git add .
          git commit -m "${{ github.event.head_commit.message }} (Automated)"
          
      - name: Git Push
        run: |
          git push origin HEAD:master -f
        
```
