### ISSUE TITLE
[cli][Report] GitHub Actions with `ubuntu-latest` Now Runs on Ubuntu 24.04, Which No Longer Includes Vercel CLI

### ISSUE THREAD

**Issue by developerjhp** [zeit/now#12801]
> **TL;DR**: If you rely on the Vercel CLI in GitHub Actions using the `ubuntu-latest` runner, be aware that it now points to Ubuntu 24.04. This version **no longer includes** the Vercel CLI by default. You must **install Vercel CLI manually** (and caching is recommended to speed things up).

---

## Background

<img width="2027" alt="image" src="https://github.com/user-attachments/assets/a448f690-e106-4d88-a7b0-809e3e468118" />

- If you attempt to run `vercel --version` or any Vercel CLI command in Github Actions using the Ubuntu 24.04 **without installing it**, you may see an error like **`exit code 127`** or **`command not found`**.

- **Ubuntu 24.04 Rollout**  [link](https://github.com/actions/runner-images/issues/10636)
  GitHub Actions’ `ubuntu-latest` label is gradually moving from Ubuntu 22.04 to **Ubuntu 24.04** between December 5th, 2024 and January 17th, 2025.  
- **Vercel CLI Removed** [link](https://github.com/actions/runner-images/issues/9848)  
  Unlike previous images (Ubuntu 20.04 or 22.04), the new 24.04 image does **not** come with Vercel CLI pre-installed.  
  Consequently, running commands like `vercel --version` (or vercel cli commands) may result in a **`command not found`** error.

---

### 1. Pin Your Workflow to Ubuntu 22.04 or 20.04

if you prefer the old environment that included Vercel CLI, you can explicity choose Ubuntu 22.04 or 20.04
```yaml
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps: ....
```

### 2. Manually Install Vercel CLI in Your Workflow

Add an installation step in your workflow:

```yaml
name: Deploy with Vercel
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vercel
        run: npm install -g vercel

      - name : .......
```

### 3. Use Caching to Speed Up Installation

To reduce install times across multiple builds, cache your npm dependencies (including Vercel):
```yaml
name: Deploy with Vercel (Cached)
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: |
          npm ci
          npm install -g vercel
          vercel --version

      - name: Deploy
        run: vercel --prod
```
If your package-lock.json (or package.json) doesn’t change often, the cache will be restored on subsequent runs, significantly speeding up the Vercel CLI installation.
