### ISSUE TITLE
Error! Failed to find deployment

### ISSUE THREAD

**Issue by AaronMcCloskey** [zeit/now#8125]
Not sure if this on the vercel side or the github action ([amondnet/vercel-action](https://github.com/amondnet/vercel-action)) i am using.

I had a successful build 4 hours ago, I then tried to redeploy with no changes to my github workflow but have now come across this error

```
Vercel CLI 27.0.1
Fetching deployment "Vercel CLI 27.0.1  (beta) — https://vercel.com/feedback\nhttps://<preview-url>.vercel.app" in mcclosa
Fetching deployment "Vercel CLI 27.0.1  (beta) — https://vercel.com/feedback\nhttps://<preview-url>.vercel.app" in mcclosa
Error! Failed to find deployment "Vercel CLI 27.0.1  (beta) — https://vercel.com/feedback\nhttps://<preview-url>.vercel.app" in mcclosa
Error! Failed to find deployment "Vercel CLI 27.0.1  (beta) — https://vercel.com/feedback\nhttps://<preview-url>.vercel.app" in mcclosa
Error: The process '/opt/hostedtoolcache/node/16.13.0/x64/bin/npx' failed with exit code 1
```

The `https://<preview-url>.vercel.app` does exist and does seem to deploy according to the vercel website but this error exits the my workflow so any further steps do not run.

This is my step to deploy to vercel.

```
- name: Deploy to Vercel
  uses: amondnet/vercel-action@v25
  id: vercel-action
  with:
    github-token: ${{ secrets.GH_TOKEN }}
    vercel-token: ${{ secrets.VERCEL_TOKEN }}
    vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
    vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
    # if main branch go to --prod environment otherwise nothing for preview environment
    vercel-args: "${{ github.ref == 'refs/heads/master' && '--prod' || '' }}"
    working-directory: ./web
```

**Comment by AaronMcCloskey** [comment]
Downgrading to `vercel` version `27.0.0` seems to work, so seems to be an issue with the [27.0.1](https://github.com/vercel/vercel/releases/tag/vercel%4027.0.1) release

**Comment by styfle** [comment]
Hi @AaronMcCloskey

Can you reproduce the error locally, without the GH Action? (we don't maintain that GH Action)

Which flags are you passing and what's the response to stdout?

**Comment by AaronMcCloskey** [comment]
I am actually unable to recreate locally, so I do think it may be on the end of the action. This is the output from the GitHub Action. (may need to zoom in, wanted to get the whole output)

<img width="2207" alt="Screenshot 2022-07-11 at 18 16 11" src="https://user-images.githubusercontent.com/20436343/178322030-5aa9674a-f382-412a-8f0a-17c5c323c6b9.png">


You can see it's probably storing this value `Vercel CLI 27.0.1  (beta) — https://vercel.com/feedback`

then proceeding to use it in the command
```
/opt/hostedtoolcache/node/16.13.0/x64/bin/npx vercel inspect Vercel CLI 27.0.1  (beta) — https://vercel.com/feedback
https://<preview-url>.vercel.app/ -t ***
```

when it should be
```
/opt/hostedtoolcache/node/16.13.0/x64/bin/npx vercel inspect https://<preview-url>.vercel.app/ -t ***
```

Here's a successful build as a comparison, using `27.0.0` you can see the `inspect` command has the correct value

<img width="724" alt="Screenshot 2022-07-11 at 18 27 08" src="https://user-images.githubusercontent.com/20436343/178323154-1949ccfe-ff11-4a29-a689-b69d34d382df.png">

**Comment by styfle** [comment]
I wonder if there is an empty string being passed as an argument causing the beta label to print

This might fix it https://github.com/vercel/vercel/pull/8129

**Comment by styfle** [comment]
Please try with Vercel CLI [27.0.2](https://github.com/vercel/vercel/releases/tag/vercel%4027.0.2)

**Comment by AaronMcCloskey** [comment]
Thanks @styfle your fix has resolved the issue!

**Comment by anasmebarki1996-c4t** [comment]
@styfle how i can use it in github action ? 
```
- name: Branching Deploy
        uses: amondnet/vercel-action@v20
        id: vercel-deploy-branching
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domains: |
            ${{ env.FRONT_APP_NAME }}
```
